// Package schema embeds the JSON Schema of the configuration file so that
// 'ghtkn json-schema' can output it. The file is generated by
// 'go run ./cmd/gen-jsonschema' and committed, so it is also served from GitHub
// for editors that refer to it by URL.
package schema

import (
	_ "embed"
)

// Schema is the content of json-schema/ghtkn.json.
//
//go:embed ghtkn.json
var Schema []byte
